spring:
  application:
    name: backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${PORT:8080}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGIN}

jwt:
  secretKey: thisIsMysecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd
  expiration: 3600000
  refreshExpiration: 2592000000
